### ISSUE TITLE
As a dev I want to save music files denoted by hash-values to have unique names. [2]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#19]
- [x] Create the hash value of the music file
- [x] Save the file named with its hash value in the local filesystem

Integrate in https://github.com/peermusic/desktop

**Comment by queicherius** [comment]
Since hashing the amount of data was taking quite long, here are some benchmarks:
- sha322 of [create-hash](https://www.npmjs.com/package/create-hash): ~2s / file
- md5 of [create-hash](https://www.npmjs.com/package/create-hash): ~2s / file
- md5 from [myersdaily](http://www.myersdaily.org/joseph/javascript/md5-text.html): ~500-700ms / file
- xxhash from [js-xxhash](https://github.com/pierrec/js-xxhash): ~100-200ms / file

I implemented xxhash, since we **really** need the speed when adding lots of files.

**Comment by queicherius** [comment]
After searching around a bit for high-performance JS hashes, I found [rusha](https://github.com/srijs/rusha).

It's even faster than xxhash (100-140ms / file), so I changed the algorithm to that.
