### ISSUE TITLE
register `web+peermusic:` in the browser

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#72]
Pass-by-URL-around wishlist:
- Invites
- Song + progress/start-at state
- ...

**Comment by queicherius** [comment]
Okay, I played around with this for a bit. It sounds absolutely great in theory, but in practice the support for it is... bad :expressionless:

Registering a protocol handle is easily done by calling `navigator.registerProtocolHandle('web+peermusic', 'http://the-domain.com', 'Peermusic')`

#### Problems :boom:
- **Windows:** The protocol handlers show up in the "manage" view, but they have "none" set as a handler and **can't be changed to the actual URL**. If you use one if the standard one's (e.g. `mailto`), it works. Searching around a lot of other people have that problem too, but I couldn't find a solution. (I didn't try the solutions recommending registry changes, because that's unacceptable for the enduser).
- **Mac:** The protocol handlers show up and have the handler set. URLs clicked in the browser work. **URLs in other applications get completely ignored however**. This breaks our actual use-case of clicking on links in mails, if the user doesn't use a browser-based solution.

What are your opinions on this @pguth @ryomiyaichi? Should we still add it, even tho our use case is way smaller than expected with this (= Mac, possibly Linux, only in web pages)? The overhead would be to implement the logic for parsing the link and adding it into the interface.

**Comment by perguth** [comment]
I took me a while to see that. On Linux it asks for permission, before accepting the handle. 
After accepting it works nice on Linux too!
![request handle permission](https://cdn.pbrd.co/images/N3TpEKU.png)  

I think this feature would be beneficial even if the handles only work within the browser: think webmail clients or social networks.  :+1:

**Comment by perguth** [comment]
We could pass around quite a bit via URL, see/edit first post.
